"""Add registration start and end dates to event

Revision ID: 29f90e07e378
Revises: 3630df9fcef3
Create Date: 2026-02-26 17:02:01.685969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f90e07e378'
down_revision: Union[str, Sequence[str], None] = '3630df9fcef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('registration_start_date', sa.String(), nullable=True))
    op.add_column('events', sa.Column('registration_end_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'registration_end_date')
    op.drop_column('events', 'registration_start_date')
    # ### end Alembic commands ###
