"""add registration to events

Revision ID: 3630df9fcef3
Revises: 6ca722610572
Create Date: 2026-02-23 11:54:40.607229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3630df9fcef3'
down_revision: Union[str, Sequence[str], None] = '6ca722610572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blog_posts_status'), 'blog_posts', ['status'], unique=False)
    op.add_column('events', sa.Column('is_registration_enabled', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('registration_fee', sa.String(), nullable=True))
    op.add_column('events', sa.Column('max_attendees', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('external_registration_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('events_slug_key'), 'events', type_='unique')
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_order'), 'events', ['order'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_gallery_items_order'), 'gallery_items', ['order'], unique=False)
    op.create_index(op.f('ix_gallery_items_type'), 'gallery_items', ['type'], unique=False)
    op.drop_column('gallery_items', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_items', sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_gallery_items_type'), table_name='gallery_items')
    op.drop_index(op.f('ix_gallery_items_order'), table_name='gallery_items')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_order'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.create_unique_constraint(op.f('events_slug_key'), 'events', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('events', 'external_registration_url')
    op.drop_column('events', 'max_attendees')
    op.drop_column('events', 'registration_fee')
    op.drop_column('events', 'is_registration_enabled')
    op.drop_index(op.f('ix_blog_posts_status'), table_name='blog_posts')
    # ### end Alembic commands ###
