"""Add ticket_id to registrations

Revision ID: 547f7850f7be
Revises: 29f90e07e378
Create Date: 2026-02-26 17:18:41.553838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547f7850f7be'
down_revision: Union[str, Sequence[str], None] = '29f90e07e378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('ticket_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_event_registrations_ticket_id'), 'event_registrations', ['ticket_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_registrations_ticket_id'), table_name='event_registrations')
    op.drop_column('event_registrations', 'ticket_id')
    # ### end Alembic commands ###
