"""add events table

Revision ID: 6ca722610572
Revises: c48a13e8fc8d
Create Date: 2026-02-20 17:54:17.055016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ca722610572'
down_revision: Union[str, Sequence[str], None] = 'c48a13e8fc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_views_id'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_page_path'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_session_id'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_table('events_backup_old')
    op.add_column('events', sa.Column('date', sa.String(), nullable=True))
    op.add_column('events', sa.Column('time', sa.String(), nullable=True))
    op.add_column('events', sa.Column('location', sa.String(), nullable=True))
    op.add_column('events', sa.Column('map_url', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('featured_image', sa.String(), nullable=True))
    op.add_column('events', sa.Column('featured_image_public_id', sa.String(), nullable=True))
    op.add_column('events', sa.Column('organizer_name', sa.String(), nullable=True))
    op.add_column('events', sa.Column('organizer_phone', sa.String(), nullable=True))
    op.add_column('events', sa.Column('organizer_email', sa.String(), nullable=True))
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'location_map')
    op.drop_column('events', 'status')
    op.drop_column('events', 'timing')
    op.drop_column('events', 'feature_image')
    op.drop_column('events', 'start_date')
    op.drop_column('events', 'feature_image_public_id')
    op.drop_column('events', 'organizer_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organizer_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('feature_image_public_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('feature_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('timing', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'published'::character varying"), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('location_map', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.alter_column('events', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('events', 'organizer_email')
    op.drop_column('events', 'organizer_phone')
    op.drop_column('events', 'organizer_name')
    op.drop_column('events', 'featured_image_public_id')
    op.drop_column('events', 'featured_image')
    op.drop_column('events', 'map_url')
    op.drop_column('events', 'location')
    op.drop_column('events', 'time')
    op.drop_column('events', 'date')
    op.create_table('events_backup_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('feature_image_public_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location_map', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('organizer_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), server_default=sa.text("'ENTERTAINMENT'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'published'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey1'))
    )
    op.create_table('page_views',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('page_views_pkey'))
    )
    op.create_index(op.f('ix_page_views_session_id'), 'page_views', ['session_id'], unique=False)
    op.create_index(op.f('ix_page_views_page_path'), 'page_views', ['page_path'], unique=False)
    op.create_index(op.f('ix_page_views_id'), 'page_views', ['id'], unique=False)
    # ### end Alembic commands ###
